config/routes.rb
Rails.application.routes.draw do

  get 'search/index'

  get 'search/show'

  root 'home#index'
  get 'home/index'

  get 'start/new'
  get 'start' => 'start#new'

  get 'catalogo/index'
  get 'catalogo/show'

  resources :sections do
    resources :preproducts do
      resources :products
    end
  end

  resources :colors

  resources :admins

  get 'access/index'

  get 'access/login'
  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/views/admins/_form.html.erb
<div class="form-group">
  <br />
  <%= error_messages_for(@admin) %>
</div>
<div class="form-group">
  <%= f.label :username, "Username", :class => "control-label" %>
	<%= f.text_field :username, :class => "form-control" %>
</div>
<div class="form-group">
	<%= f.label :email, "Email", :class => "control-label" %>
	<%= f.text_field :email, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :password, "Password", :class => "control-label" %>
  <%= f.password_field :password, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label :password_confirmation, "Password confirmation", :class => "control-label" %>
  <%= f.password_field :password_confirmation, :class => "form-control" %>
</div>
<% if session[:super_admin] and @admin.id != session[:admin_id] %>
  <div class="form-group">
    <%= f.label :active, "Activo", :class => "control-label" %>
    <%= f.check_box(:active) %>
  </div>
<% end %>

app/views/admins/delete.html.erb
<% @page_title = "Admin" %>

<%= link_to("<< Back to List", {:action => 'index'}, :class => 'back-link') %>

<div class="admin delete">
	<h2>Delete Admin</h2>

	<%= form_for(:admin, :url => {:action => 'destroy', :id => @admin.id}) do |f| %>

		<p>Are you sure you want to permanently delete this admin?</p>

		<p class="reference-name"><%= @admin.username %></p>

		<div class="form-buttons">
			<%= submit_tag("Delete Admin") %>
		</div>
		
	<% end %>
</div>

app/views/admins/edit.html.erb
<% @page_title = "Edit Admin" %>

<div>
  <ul class="pager">
      <li class="previous">
        <%= link_to admins_path do %>
          <span aria-hidden='true'>&larr;</span> Volver al listado
        <% end %>
      </li>
    </ul>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Edit Admin</h3>
      </div>
      <div class="panel-body">
        <%= form_for(:admin, :url => admin_path(@admin.id), :method => :patch) do |f| %>
          <%= render(:partial => "form", :locals => {:f => f}) %>
          <%= submit_tag("Update Admin", :class => "btn btn-primary") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admins/index.html.erb
<% @page_title = "Admins" %>

<div>
	<ul class="pager">
    	<li class="previous">
				<%= link_to access_index_path do %>
   				<span aria-hidden='true'>&larr;</span> Volver al menu
				<% end %>
			</li>
			<li class="next">
				<%= link_to new_admin_path do %>
   				<b>+</b> Añadir administrador
				<% end %>
			</li>
		</ul>
</div>

<div class="panel panel-info">
<!-- Default panel contents -->
	<div class="panel-heading">
		<h4><%= pluralize(@admins.size, 'administrador encontrado' ,'administradores encontrados') %></h4>
	</div>
	<!-- Table -->
	<table class="table">
		<tr>
			<th>Username</th>
			<th>Email</th>
			<th>Activo</th>
			<th>Creado</th>
			<th>Acción</th>
		</tr>
		<% @admins.each do |admin| %>
			<tr class="<%= cycle('odd','even')%>">
				<td><%= admin.username %></td>
				<td><%= admin.email %></td>
				<td><%= status_tag(admin.active) %></td>
				<td><%= admin.created_at %></td>
				<td>
					<div class="btn-group" role="group" aria-label="...">
						<%= link_to("Editar", edit_admin_path(admin.id), :class => 'btn btn-default btn-sm') %>
						<%= link_to('Borrar', admin_path(admin.id), method: :delete, data: { confirm: '¿Estas seguro que quieres borrar el usuario admin?' }, :class => 'btn btn-default btn-sm') %>
					</div>
				</td>
			</tr>
		<% end %>
	</table>
</div>

app/views/admins/new.html.erb
<% @page_title = "new Admin Users" %>

<div>
  <ul class="pager">
      <li class="previous">
        <%= link_to admins_path do %>
          <span aria-hidden='true'>&larr;</span> Volver al listado
        <% end %>
      </li>
    </ul>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Create Admin</h3>
      </div>
      <div class="panel-body">
        <%= form_for(:admin, :url => {:action => 'create'}) do |f| %>
      		<%= render(:partial => "form", :locals => {:f => f}) %>
      		<%= submit_tag("Create Admin", :class => "btn btn-primary") %>
        <% end %>
      </div>
    </div>
  </div>
</div>