config/routes.rb
Rails.application.routes.draw do

  get 'search/index'

  get 'search/show'

  root 'home#index'
  get 'home/index'

  get 'start/new'
  get 'start' => 'start#new'

  get 'catalogo/index'
  get 'catalogo/show'

  resources :sections do
    resources :preproducts do
      resources :products
    end
  end

  resources :colors

  resources :admins

  get 'access/index'

  get 'access/login'
  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/preproduct.rb
class Preproduct < ActiveRecord::Base

  belongs_to :section
  has_many :products
  has_many :colors, through: :products
  
  validates_presence_of :titulo
  validates_length_of :titulo, :maximum => 75
  validates_presence_of :ref_pre
  validates_uniqueness_of :ref_pre
  validates_length_of :ref_pre, :maximum => 10
  validates_presence_of :section_id

  scope :sorted, lambda { order("preproducts.ref_pre ASC") }

end

app/controllers/preproducts_controller.rb
class PreproductsController < ApplicationController

  before_action :confirm_logged_in
  before_action :find_section

  def index
    @preproducts = @section.preproducts.sorted
  end

  def show
    @preproduct = Preproduct.find(params[:id])
  end

  def new
    @preproduct = Preproduct.new({:section_id => @section.id})
    @sections = Section.order('id ASC')
  end

  def create
    @preproduct = Preproduct.new(preproduct_params)
    #guardamos el preproduct
    if @preproduct.save
      #Si se ha guardado, redirigimos a la página de listado de preproducts de la categoría
      flash[:notice] = "Preproduct creado con éxito."
      redirect_to section_preproducts_path(@preproduct.section_id)
    else
      # Si hay algún error, volvemos al formulario
      @sections = Section.order('id ASC')
      render('new')
    end
  end

  def edit
    @preproduct = Preproduct.find(params[:id])
    @sections = Section.order('id ASC')
  end

  def update
    # buscamos el preproduct
    @preproduct = Preproduct.find(params[:id])
    # Actualizamos el preproduct
    if @preproduct.update_attributes(preproduct_params)
      # Si se actualiza correctamente, redirigimos al listado de preproducts de la categoría
      flash[:notice] = "Preproduct actualizado con éxito."
      redirect_to section_preproducts_path(@preproduct.section_id)
    else
      # Si hay algún error, volvemos al formulario
      @sections = Section.order('id ASC')
      render('edit')
    end
  end

  def delete
    @preproduct = Preproduct.find(params[:id])
  end

  def destroy
    @preproduct = Preproduct.find(params[:id]).destroy
    flash[:notice] = "Preproduct '#{@preproduct.titulo}' borrado con éxito."
    redirect_to section_preproducts_path(@preproduct.section_id)
  end

  private

    def preproduct_params
      params.require(:preproduct).permit(:section_id, :titulo, :descripcion, :precio, :ref_pre)
    end

    def find_section
      if params[:section_id]
        @section = Section.find(params[:section_id])
      end
    end
end

app/helpers/preproducts_helper.rb
module PreproductsHelper
end

app/views/preproducts/_form.html.erb
<div class="form-group">
  <%= error_messages_for(@preproduct) %>
</div>
<div class="form-group">
  <%= f.label(:section_id, "Sección", :class => "control-label") %>
  <%= f.select(:section_id, @sections.map {|s| [s.titulo, s.id]}, {}, :class => "form-control") %>
</div>
<div class="form-group">
  <%= f.label(:titulo, "Título", :class => "control-label") %>
  <%= f.text_field :titulo, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label(:descripcion, "Descripción", :class => "control-label") %>
  <%= f.text_field :descripcion, :size => "40x5", :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label(:ref_pre, "Referencia", :class => "control-label") %>
  <%= f.text_field :ref_pre, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label(:precio, "Precio sin €", :class => "control-label") %>
  <%= f.text_field :precio, :class => "form-control" %>
</div>

app/views/preproducts/delete.html.erb
<% @page_title = "PreProducto" %>

<%= link_to("<< Volver al listado", section_preproducts_path(@section.id), :class => 'back-link') %>

<div class="subject delete">
	<h2>Borrar PreProducto</h2>

	<%= form_for(:preproduct, :url => section_preproduct_path(@section.id, @preproduct.id), :method => :delete) do |f| %>

		<p>¿Estas seguro que quieres borrar este PreProducto?</p>

		<p class="reference-name"><%= @preproduct.titulo %></p>

		<div class="form-buttons">
			<%= submit_tag("Borrar PreProducto") %>
		</div>
		
	<% end %>
</div>

app/views/preproducts/edit.html.erb
<% @page_title = "PreProducto" %>

<div>
  <ul class="pager">
    <li class="previous">
      <%= link_to section_preproducts_path(@section.id) do %>
        <span aria-hidden='true'>&larr;</span> Volver al listado
      <% end %>
    </li>
  </ul>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Actualizar Preproducto</h3>
      </div>
      <div class="panel-body">
        <%= form_for(:preproduct, :url => section_preproduct_path(@section.id, @preproduct.id), :method => :patch) do |f| %>
        <%= render(:partial => "form", :locals => {:f => f}) %>
        <div class="form-buttons">
          <%= submit_tag("Actualizar PreProducto", :class => "btn btn-primary") %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/preproducts/index.html.erb
<% @page_title = "PreProductos" %>

<div>
	<ul class="pager">
    	<li class="previous">
				<%= link_to sections_path do %>
   				<span aria-hidden='true'>&larr;</span> Volver al listado
				<% end %>
			</li>
			<li class="next">
				<%= link_to new_section_preproduct_path(@section.id) do %>
   				<b>+</b> Añadir nuevo preproducto
				<% end %>
			</li>
		</ul>
</div>
<div class="panel panel-info">
<!-- Default panel contents -->
<div class="panel-heading">
	<h4><%= pluralize(@section.preproducts.size, 'preproducto encontrado', 'preproductos encontrados') %> de <%= @section.titulo %></h4>
</div>
<!-- Table -->
<table class="table">
	<tr>
		<th>Título</th>
		<th>Descripción</th>
		<th>Precio</th>
		<th>Colores</th>
		<th colspan="2">Acción</th>
	</tr>
	<% @preproducts.each do |preproduct| %>
	<tr class="<%= cycle('odd','even')%>">
		<td><%= preproduct.titulo %><br /><br />Referencia: <%= preproduct.ref_pre %></td>
		<td><%= preproduct.descripcion %></td>
		<td><%= number_to_currency(preproduct.precio, :precision => 1, :unit => "€", :format => "%n %u") %></td>
		<td><%= preproduct.products.size %></td>
		<td>
			<div class="btn-group-vertical" role="group" aria-label="...">
				<%= link_to("Ver productos", section_preproduct_products_path(@section.id, preproduct.id), :class => 'btn btn-default btn-sm') %>
				<%= link_to("Mostrar", section_preproduct_path(@section.id, preproduct.id), :class => 'btn btn-default btn-sm') %>
			</div>
			<div class="btn-group-vertical" role="group" aria-label="...">
				<%= link_to("Editar", edit_section_preproduct_path(@section.id, preproduct.id), :class => 'btn btn-default btn-sm') %>
				<%= link_to('Borrar', section_preproduct_path(@section.id, preproduct.id), method: :delete, data: { confirm: '¿Estas seguro que quieres borrar el preproducto?' }, :class => 'btn btn-default btn-sm') %>
			</div>
		</td>
	</tr>
	<% end %>
</table>
</div>

app/views/preproducts/new.html.erb
<% @page_title = "PreProducto" %>

<div>
  <ul class="pager">
    <li class="previous">
      <%= link_to section_preproducts_path(@section.id) do %>
        <span aria-hidden='true'>&larr;</span> Volver al listado
      <% end %>
    </li>
  </ul>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Crear preproducto</h3>
      </div>
      <div class="panel-body">
        <%= form_for(:preproduct, :url => section_preproducts_path(@section.id), :method => :post) do |f| %>
        <%= render(:partial => "form", :locals => {:f => f}) %>
        <div class="form-buttons">
          <%= submit_tag("Crear PreProducto", :class => "btn btn-primary") %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/preproducts/show.html.erb
<% @page_title = "PreProducto" %>

<div>
	<ul class="pager">
  	<li class="previous">
			<%= link_to section_preproducts_path(@section.id) do %>
 				<span aria-hidden='true'>&larr;</span> Volver al listado
			<% end %>
		</li>
	</ul>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Mostrar PreProducto</h3>
      </div>
      <div class="panel-body">
      	<table class="table">
        	<tr>
        		<th>Sección:</th>
        		<td><%= @section.titulo %></td>
        	</tr>
        	<tr>
        		<th>Título:</th>
        		<td><%= @preproduct.titulo %></td>
        	</tr>
        	<tr>
        		<th>Descripción:</th>
        		<td><%= @preproduct.descripcion %></td>
        	</tr>
        	<tr>
        		<th>Referencia:</th>
        		<td><%= @preproduct.ref_pre %></td>
        	</tr>
        	<tr>
        		<th>Precio:</th>
        		<td><%= number_to_currency(@preproduct.precio, :precision => 1, :unit => "€", :format => "%n %u") %></td>
        	</tr>
        	<tr>
						<th>Creado:</th>
						<td><%= @preproduct.created_at %></td>
        	</tr>
        	<tr>
						<th>Actualizado:</th>
						<td><%= @preproduct.updated_at %></td>
        	</tr>
        </table>
      </div>
    </div>
  </div>
</div>
		<!--
		<tr>
			<th>Visible?</th>
			<td><= @preproduct.visible ? 'true' : 'false' %></td>
		</tr>
		-->