config/routes.rb
Rails.application.routes.draw do

  get 'search/index'

  get 'search/show'

  root 'home#index'
  get 'home/index'

  get 'start/new'
  get 'start' => 'start#new'

  get 'catalogo/index'
  get 'catalogo/show'

  resources :sections do
    resources :preproducts do
      resources :products
    end
  end

  resources :colors

  resources :admins

  get 'access/index'

  get 'access/login'
  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/section.rb
class Section < ActiveRecord::Base

  has_many :preproducts

  has_attached_file :image,
    :styles => {
    :thumb    => ['100x100',  :jpg, :quality => 70],
    :preview  => ['290x290',  :jpg, :quality => 70],
    :standard => ['400x400',  :jpg, :quality => 70]
  },
  :convert_options => {
    :thumb    => '-set colorspace sRGB -strip',
    :preview  => '-set colorspace sRGB -strip',
    :standard => '-set colorspace sRGB -strip'
  }

  validates_presence_of :titulo
  validates_length_of :titulo, :maximum => 50
  validates_presence_of :ref_sec
  validates_uniqueness_of :ref_sec
  validates_length_of :ref_sec, :maximum => 5

  scope :sorted, lambda { order("sections.id ASC") }

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  
  before_action :confirm_logged_in

  def index
    @sections = Section.sorted
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)
    #guardamos la sección
    if @section.save
      #Si se guarda correctamente, redirigimos a index
      flash[:notice] = "Sección creada con éxito."
      redirect_to sections_path
    else
      #Si el guardar tiene algún error, volvemos a mostrar el formulario para solucionarlo
      render('new')
    end
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    #encontrar sección
    @section = Section.find(params[:id])
    #actualizar sección
    if @section.update_attributes(section_params)
      #Si se actualiza correctamente, redirigimos a index
      flash[:notice] = "Sección actualizada con éxito."
      redirect_to sections_path
    else
      #Si el actualizar tiene algún error, volvemos a mostrar el formulario para solucionarlo
      render('edit')
    end
  end

  def delete
    @section = Section.find(params[:id])
  end
    
  def destroy
    @section = Section.find(params[:id]).destroy
    flash[:notice] = "La sección '#{@section.titulo}' ha sido borrada con éxito."
    redirect_to sections_path
  end

  private

    def section_params
      params.require(:section).permit(:titulo, :titular, :ref_sec, :image)
    end

end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
<div class="form-group">
  <%= error_messages_for(@section) %>
</div>
<div class="form-group">
  <%= f.label(:titulo, "Título", :class => "control-label") %>
  <%= f.text_field :titulo, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label(:titular, "Descripción", :class => "control-label") %>
  <%= f.text_field :titular, :size => "40x5", :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label(:ref_sec, "Referencia", :class => "control-label") %>
  <%= f.text_field :ref_sec, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label(:image, "Imagen", :class => "control-label") %>
  <%= image_tag @section.image.url(:thumb) if @section.image? %>
  <%= f.file_field :image, :title => "Busca una imagen para subir" %>
</div>

app/views/sections/delete.html.erb
<% @page_title = "Section" %>

<%= link_to("<< Volver al listado", sections_path, :class => 'back-link') %>

<div class="subject delete">
	<h2>Borrar sección</h2>

	<%= form_for(:section, :url => section_path(@section.id), :method => :delete) do |f| %>

		<p>¿Estas seguro que quieres borrar esta sección?</p>

		<p class="reference-name"><%= @section.titulo %></p>

		<div class="form-buttons">
			<%= submit_tag("Borrar sección") %>
		</div>
		
	<% end %>
</div>

app/views/sections/edit.html.erb
<% @page_title = "Sección" %>

<div>
  <ul class="pager">
    <li class="previous">
      <%= link_to sections_path do %>
        <span aria-hidden='true'>&larr;</span> Volver al listado
      <% end %>
    </li>
  </ul>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Actualizar Sección</h3>
      </div>
      <div class="panel-body">
        <%= form_for(:section, :url => section_path(@section.id), :html => { :multipart => true }, :method => :patch) do |f| %>
        <%= render(:partial => "form", :locals => {:f => f}) %>
        <div class="form-buttons">
          <%= submit_tag("Actualizar sección", :class => "btn btn-primary") %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/sections/index.html.erb
<% @page_title = "Secciones" %>

<div>
	<ul class="pager">
    	<li class="previous">
				<%= link_to access_index_path do %>
   				<span aria-hidden='true'>&larr;</span> Volver al menu
				<% end %>
			</li>
			<li class="next">
				<%= link_to new_section_path do %>
   				<b>+</b> Añadir nueva sección
				<% end %>
			</li>
		</ul>
</div>
<div class="panel panel-info">
<!-- Default panel contents -->
<div class="panel-heading">
	<h4><%= pluralize(@sections.size, 'Sección encontrada' ,'Secciones encontradas') %></h4>
</div>
<!-- Table -->
<table class="table">
	<tr>
		<th>Sección</th>
		<th>Descripción</th>
		<th>Imagen</th>
		<th>PreProductos</th>
		<th colspan="2">Acción</th>
	</tr>
	<% @sections.each do |section| %>
	<tr class="<%= cycle('odd','even')%>">
		<td><%= section.titulo %><br /><br />Referencia: <%= section.ref_sec %></td>
		<td><%= section.titular %></td>
		<td><%= image_tag section.image.url(:thumb) %></td>
		<td><%= section.preproducts.size %></td>
		<td>
			<div class="btn-group-vertical" role="group" aria-label="...">
				<%= link_to("Ver PreProductos", section_preproducts_path(section.id), :class => 'btn btn-default btn-sm') %>
				<%= link_to("Mostrar", section_path(section.id), :class => 'btn btn-default btn-sm') %>
			</div>
		</td>
		<td>
			<div class="btn-group-vertical" role="group" aria-label="...">
				<%= link_to("Editar", edit_section_path(section.id), :class => 'btn btn-default btn-sm') %>
				<%= link_to('Borrar', section_path(section.id), method: :delete, data: { confirm: '¿Estas seguro que quieres borrar la sección?' }, :class => 'btn btn-default btn-sm') %>
			</div>
		</td>
	</tr>
	<% end %>
</table>
</div>

app/views/sections/new.html.erb
<% @page_title = "Section" %>

<div>
  <ul class="pager">
    <li class="previous">
      <%= link_to sections_path do %>
        <span aria-hidden='true'>&larr;</span> Volver al listado
      <% end %>
    </li>
  </ul>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Crear sección</h3>
      </div>
      <div class="panel-body">
        <%= form_for(:section, :url => sections_path, :method => :post) do |f| %>
        <%= render(:partial => "form", :locals => {:f => f}) %>
        <div class="form-buttons">
          <%= submit_tag("Crear categoría", :class => "btn btn-primary") %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/sections/show.html.erb
<% @page_title = "Sección" %>

<div>
	<ul class="pager">
  	<li class="previous">
			<%= link_to sections_path do %>
 				<span aria-hidden='true'>&larr;</span> Volver al listado
			<% end %>
		</li>
	</ul>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Mostrar sección</h3>
      </div>
      <div class="panel-body">
      	<table class="table">
        	<tr>
        		<th>Título:</th>
        		<td><%= @section.titulo %></td>
        	</tr>
        	<tr>
        		<th>Descripción:</th>
        		<td><%= @section.titular %></td>
        	</tr>
        	<tr>
        		<th>Referencia:</th>
        		<td><%= @section.ref_sec %></td>
        	</tr>
        	<tr>
        		<th>Imagen:</th>
        		<td><%= image_tag @section.image.url(:preview) %></td>
        	</tr>
        	<tr>
						<th>Creada:</th>
						<td><%= @section.created_at %></td>
        	</tr>
        	<tr>
						<th>Actualizada:</th>
						<td><%= @section.updated_at %></td>
        	</tr>
        </table>
      </div>
    </div>
  </div>
</div>