config/routes.rb
Rails.application.routes.draw do

  get 'search/index'

  get 'search/show'

  root 'home#index'
  get 'home/index'

  get 'start/new'
  get 'start' => 'start#new'

  get 'catalogo/index'
  get 'catalogo/show'

  resources :sections do
    resources :preproducts do
      resources :products
    end
  end

  resources :colors

  resources :admins

  get 'access/index'

  get 'access/login'
  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/product.rb
class Product < ActiveRecord::Base

	belongs_to :color
	belongs_to :preproduct
  belongs_to :product

  before_save :comprobar_referencia
  before_save :default_titulo, :unless => :titulo?
  before_save :default_descripcion, :unless => :descripcion?
  before_save :default_precio, :unless => :precio?
  before_save :default_referencia
  
  has_attached_file :image,
    :styles => {
    :thumb    => ['100x100',  :jpg, :quality => 70],
    :preview  => ['250x250',  :jpg, :quality => 70],
    :standard => ['400x400',  :jpg, :quality => 70],
    :large    => ['600>',     :jpg, :quality => 60]
  },
  :convert_options => {
    :thumb    => '-set colorspace sRGB -strip',
    :preview  => '-set colorspace sRGB -strip',
    :standard => '-set colorspace sRGB -strip',
    :large    => '-set colorspace sRGB -strip -sharpen 0x0.5'
  }

	scope :sorted, lambda { order("products.ref_pro ASC") }
  scope :next, ->(product) { where("ref_pro > ?", product.ref_pro).sorted }
  scope :previous, ->(product) { where("ref_pro < ?", product.ref_pro).sorted }

  private

    def default_titulo
      if self.color.ref_col == "NC"
        self.titulo = "#{self.preproduct.titulo}"
      else
        self.titulo = "#{self.preproduct.titulo} #{self.color.color}"
      end
    end

    def default_descripcion
      self.descripcion = "#{self.preproduct.descripcion}"
    end

    def default_precio
      self.precio = "#{self.preproduct.precio}"
    end

    def comprobar_referencia
      # if producto = Product.exists?(ref_pro: "#{self.preproduct.section.ref_sec}#{self.preproduct.ref_pre}#{self.color.ref_col}")
      cantidad = Product.where(ref_pro: "#{self.preproduct.section.ref_sec}#{self.preproduct.ref_pre}#{self.color.ref_col}").where("id != #{self.id}")
      if cantidad.size > 0
        errors.add(:ref_pro, "El producto ya existe") 
        return false
      end
    end

    def default_referencia
      self.ref_pro =  "#{self.preproduct.section.ref_sec}#{self.preproduct.ref_pre}#{self.color.ref_col}"
    end

    def self.search(search)
      result = where('titulo LIKE ?', "%#{search}%")
      result += where('descripcion LIKE ?', "%#{search}%")
      result += where('ref_pro LIKE ?', "%#{search}%")
      result.uniq
      result = result.sort_by &:ref_pro
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  layout 'application'

  before_action :confirm_logged_in
  before_action :find_section, :find_preproduct

  def index
    @products = @preproduct.products.sorted
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new({:preproduct_id => @preproduct.id})
    @preproducts = Preproduct.order('ref_pre ASC')
    @colors = Color.order('ref_col ASC')
  end

  def create
    @product = Product.new(product_params)
    #guardamos el product
    if @product.save
      #Si se ha guardado, redirigimos a la página de listado de products del preproduct
      flash[:notice] = "Producto creado con éxito."
      redirect_to section_preproduct_products_path(@section.id, @product.preproduct_id)
    else
      # Si hay algún error, volvemos al formulario
      @preproducts = Preproduct.order('ref_pre ASC')
      @colors = Color.order('ref_col ASC')
      render('new')
    end
  end

  def edit
    @product = Product.find(params[:id])
    @preproducts = Preproduct.order('ref_pre ASC')
    @colors = Color.order('ref_col ASC')
  end

  def update
    # buscamos el product
    @product = Product.find(params[:id])
    # Actualizamos el product
    if @product.update_attributes(product_params)
      # Si se actualiza correctamente, redirigimos al listado de products del preproduct
      flash[:notice] = "Producto actualizado con éxito."
      redirect_to section_preproduct_products_path(@section.id, @product.preproduct_id)
    else
      # Si hay algún error, volvemos al formulario
      @preproducts = Preproduct.order('ref_pre ASC')
      @colors = Color.order('ref_col ASC')
      render('edit')
    end
  end

  def delete
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id]).destroy
    flash[:notice] = "Producto borrado con éxito."
    redirect_to section_preproduct_products_path(@section.id, @product.preproduct_id)
  end

  private

    def product_params
      params.require(:product).permit(:preproduct_id, :color_id, :titulo, :descripcion, :precio, :image)
    end

    def find_preproduct
      if params[:preproduct_id]
        @preproduct = Preproduct.find(params[:preproduct_id])
      end
    end

    def find_section
      if params[:section_id]
        @section = Section.find(params[:section_id])
      end
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="form-group">
  <%= error_messages_for(@product) %>
</div>
<div class="form-group">
  <%= f.label(:preproduct_id, "Preproducto", :class => "control-label") %>
  <%= f.select :preproduct_id, @section.preproducts.map {|p| [p.titulo, p.id]}, {}, {:class => "form-control"} %>
</div>
<div class="form-group">
  <%= f.label(:color_id, "Color", :class => "control-label") %>
  <%= f.select :color_id, @colors.map {|c| [c.color, c.id]}, {}, {:class => "form-control"} %>
</div>
<div class="form-group">
  <%= f.label(:titulo, "Título", :class => "control-label") %>
  <%= f.text_field :titulo, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label(:descripcion, "Descripción") %>
  <%= f.text_area :descripcion, :size => "40x5", :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label(:precio, "Precio", :class => "control-label") %>
  <%= f.text_field :precio, :class => "form-control" %>
</div>
<div class="form-group">
  <%= f.label(:image, "Imagen") %>
  <%= image_tag @product.image.url(:thumb) if @product.image? %>
  <%= f.file_field :image, :title => "Buscar imagen" %>
</div>

app/views/products/delete.html.erb
<% @page_title = "PreProducto" %>
<%= link_to("<< Volver al listado", section_preproducts_path(@section.id), :class => 'back-link') %>

<div class="subject delete">
	<h2>Borrar PreProducto</h2>

	<%= form_for(:preproduct, :url => section_preproduct_path(@section.id, @preproduct.id), :method => :delete) do |f| %>

		<p>¿Estas seguro que quieres borrar este PreProducto?</p>

		<p class="reference-name"><%= @preproduct.titulo %></p>

		<div class="form-buttons">
			<%= submit_tag("Borrar PreProducto") %>
		</div>
		
	<% end %>
</div>

app/views/products/edit.html.erb
<% @page_title = "Editar Producto" %>

<div>
  <ul class="pager">
    <li class="previous">
      <%= link_to section_preproduct_products_path(@section.id,@preproduct.id) do %>
        <span aria-hidden='true'>&larr;</span> Volver al listado
      <% end %>
    </li>
  </ul>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Actualizar Producto</h3>
      </div>
      <div class="panel-body">
        <%= form_for(:product, :url => section_preproduct_products_path(@section.id, @preproduct.id), :html => { :multipart => true }, :method => :patch) do |f| %>
          <%= render(:partial => "form", :locals => {:f => f}) %>
        <div class="form-buttons">
          <%= submit_tag("Actualizar Producto", :class => "btn btn-primary") %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<% @page_title = "Productos" %>

<div>
	<ul class="pager">
    	<li class="previous">
				<%= link_to section_preproducts_path(@section.id) do %>
   				<span aria-hidden='true'>&larr;</span> Volver al listado
				<% end %>
			</li>
			<li class="next">
				<%= link_to new_section_preproduct_product_path(@section.id, @preproduct.id) do %>
   				<b>+</b> Añadir nuevo producto
				<% end %>
			</li>
		</ul>
</div>
<div class="panel panel-info">
<!-- Default panel contents -->
<div class="panel-heading">
	<h4><%= pluralize(@preproduct.products.size, 'Producto encontrado', 'Productos encontrados') %> de <%= @preproduct.titulo %></h4>
</div>
<!-- Table -->
<table class="table">
	<tr>
		<th>Título</th>
		<th>Descripción</th>
		<th>Precio</th>
		<th>Imagen</th>
		<th>Acción</th>
	</tr>
	<% @products.each do |product| %>
	<tr class="<%= cycle('odd','even')%>">
		<td><%= product.titulo %><br /><br />Referencia: <%= product.ref_pro %></td>
		<td><%= product.descripcion %></td>
		<td><%= number_to_currency(product.precio, :precision => 1, :unit => "€", :format => "%n %u") %></td>
		<td><%= image_tag product.image.url(:thumb), :alt => product.titulo, :title => product.titulo %></td>
		<td>
			<div class="btn-group-vertical" role="group" aria-label="...">
				<%= link_to("Mostrar", section_preproduct_product_path(@section.id, @preproduct.id, product.id), :class => 'btn btn-default btn-sm') %>
				<%= link_to("Editar", edit_section_preproduct_product_path(@section.id, @preproduct.id, product.id), :class => 'btn btn-default btn-sm') %>
				<%= link_to('Borrar', section_preproduct_product_path(@section.id, @preproduct.id, product.id), method: :delete, data: { confirm: '¿Estas seguro que quieres borrar el producto?' }, :class => 'btn btn-default btn-sm') %>
			</div>
		</td>
	</tr>
	<% end %>
</table>
</div>

app/views/products/new.html.erb
<% @page_title = "Nuevo Producto" %>

<div>
  <ul class="pager">
    <li class="previous">
      <%= link_to section_preproduct_products_path(@section.id,@preproduct.id) do %>
        <span aria-hidden='true'>&larr;</span> Volver al listado
      <% end %>
    </li>
  </ul>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Crear Producto</h3>
      </div>
      <div class="panel-body">
        <%= form_for(:product, :url => section_preproduct_products_path(@section.id, @preproduct.id), :html => { :multipart => true }, :method => :post) do |f| %>
          <%= render(:partial => "form", :locals => {:f => f}) %>
        <div class="form-buttons">
          <%= submit_tag("Crear Producto", :class => "btn btn-primary") %>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<% @page_title = "Producto" %>

<div>
	<ul class="pager">
  	<li class="previous">
			<%= link_to section_preproduct_products_path(@section.id,@preproduct.id) do %>
 				<span aria-hidden='true'>&larr;</span> Volver al listado
			<% end %>
		</li>
	</ul>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">Mostrar producto</h3>
      </div>
      <div class="panel-body">
      	<table class="table">
      		<tr>
        		<th>Preproducto:</th>
        		<td><%= @preproduct.titulo %></td>
        	</tr>
        	<tr>
        		<th>Título:</th>
        		<td><%= @product.titulo %></td>
        	</tr>
        	<tr>
        		<th>Descripción:</th>
        		<td><%= @product.descripcion %></td>
        	</tr>
        	<tr>
        		<th>Referencia:</th>
        		<td><%= @product.ref_pro %></td>
        	</tr>
        	<tr>
        		<th>Imagen:</th>
        		<td><%= image_tag @product.image.url(:preview) %></td>
        	</tr>
        	<tr>
        		<th>Precio:</th>
        		<td><%= number_to_currency(@product.precio, :precision => 1, :unit => "€", :format => "%n %u") %></td>
        	<tr>
						<th>Creado:</th>
						<td><%= @product.created_at %></td>
        	</tr>
        	<tr>
						<th>Actualizado:</th>
						<td><%= @product.updated_at %></td>
        	</tr>
        </table>
      </div>
    </div>
  </div>
</div>